[project]
name = "oma-helen-ha-integration"
version = "2.2.0"
description = "Home Assistant custom integration for Helen Energy electricity service"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[dependency-groups]
dev = [
    "pytest-homeassistant-custom-component==0.13.205",
    "responses>=0.22.0",
    "oma-helen-cli==1.8.0",
]

[tool.uv]
prerelease = "allow"
